### ISSUE TITLE
Update Mapbox API Endpoint

### ISSUE THREAD

**Issue by devashish9** [sandboxnu/nucarpool#1]
**Problems**
1. Carpool currently uses [mapbox](https://docs.mapbox.com/) for custom online map generation. However, the renders it gives are limited. 
2. Interaction with the Mapbox API happens through axios, while the rest of the codebase uses trpc for APIs. 
Fix: 

- [x] Research alternatives for Mapbox
- [x] If no viable alternatives are found, analyze existing Mapbox logic in code and whether it can be improved in any manner
- [x] Implement trpc switch for mapbox API
- [x] Add documentation to trpc and mapbox code where necessary

**Comment by dillydally414** [comment]
Mapbox Alternatives - no thx lol
