### ISSUE TITLE
Backend Documentation

### ISSUE THREAD

**Issue by devashish9** [sandboxnu/nucarpool#2]
**Problem**
The backend is well made but not well documented. Makes it difficult to understand what's happening where

**Fix**

- [x] Add documentation to the schema.prisma file, and the server folder. 
- [x] Perform any code cleanup as deemed appropriate

**Comment by lukejianu** [comment]
Added a bit of explanation on Notion and added a README in the server/db folder explaining Prisma (on backend-docs branch). Dillon + others explained tRPC well, so I think backend is documented enough for now. If we need to go more in-depth, we can do it later.
